[module/menu]
type = custom/menu
expand-right = true
menu-0-0 =󱁴  Apps
menu-0-0-exec = rofi -show drun &
menu-0-1 =  Files
menu-0-1-exec = thunar &
menu-0-2 =  Terminal
menu-0-2-exec = kitty &
menu-0-3 =  Browser
menu-0-3-exec = chromium &
format = <label-toggle> <menu>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-overline = ${colors.background}
format-underline = ${colors.background}
format-padding = 2
label-open = 󰹯
label-close = 󰹯
label-separator = " | "

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = false
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = true
reverse-scroll = false
fuzzy-match = true

;ws-icon-0 = 1;  
;ws-icon-1 = 2;  
;ws-icon-2 = 3;  
;ws-icon-3 = 4;  
;ws-icon-4 = 5;  
;ws-icon-5 = 6;  
;ws-icon-6 = 7;  
;ws-icon-7 = 8;󰨞  
;ws-icon-8 = 9;  
;ws-icon-9 = 10;10 
;ws-icon-default = 1

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-mode-foreground = ${colors.background}
label-mode-background = ${colors.alert}
label-focused = %index%
label-focused-foreground = ${colors.background}
label-focused-background = ${colors.foreground}
label-focused-padding = 1
label-unfocused = %index%
label-unfocused-padding = 1
label-visible = %index%
label-visible-padding = 1
label-urgent = %index%
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.background}
label-urgent-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.blue}
format-volume = <label-volume>
label-volume = %percentage%%
format-muted-prefix = "  "
format-muted-prefix-foreground = ${colors.red}
label-muted = muted
label-muted-foreground = ${colors.foreground}
label-indicator-background = ${colors.background}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.magenta}
label = %gb_used% %percentage_used%%
label-foreground = ${colors.foreground}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.green}
label = %percentage:2%%
label-foreground = ${colors.foreground}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%  %upspeed%  %downspeed%

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
format-prefix = "  "
format-prefix-foreground = ${colors.cyan}
label = %date%
label-foreground = ${colors.foreground}

[module/powermenu]
type = custom/menu
expand-right = true

menu-0-0 = lock
menu-0-0-exec = #powermenu.open.1

menu-0-1 = logout
menu-0-1-exec = #powermenu.open.2

menu-0-2 = reboot
menu-0-2-exec = #powermenu.open.3

menu-0-3 = shutdown
menu-0-3-exec = #powermenu.open.4

menu-1-0 = back
menu-1-0-exec = #powermenu.open.0
menu-1-1 = lock
menu-1-1-exec = dm-tool lock

menu-2-0 = back
menu-2-0-exec = #powermenu.open.0
menu-2-1 = logout
menu-2-1-exec = i3-msg exit

menu-3-0 = back
menu-3-0-exec = #powermenu.open.0
menu-3-1 = reboot
menu-3-1-exec = systemctl reboot

menu-4-0 = back
menu-4-0-exec = #powermenu.open.0
menu-4-1 = shutdown
menu-4-1-exec = systemctl poweroff

format = <label-toggle> <menu>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-overline = ${colors.background}
format-underline = ${colors.background}
format-padding = 2

label-open = 
label-close =  
label-separator = " | "

